// src/components/DM/charts/townTraitsChart.js
// HexCrawl Expanded Charts v1.0 — Town Traits (D36 = D6×10+D6)
// Roll twice when entering a town for the first time (once if Frontier Town expansion).
// Do not re-roll for subsequent visits to the same town.

export const townTraitsChart = [
  { roll: 11, name: "Dry", flavor: "Heroes may not purchase alcoholic Side Bag Tokens here.", effect: "Heroes may not purchase alcoholic Side Bag Tokens here, but may try to sell them at the Campsite for 2× the price. When trying to sell, roll D6. On a 1 or 2, the sale is discovered and the Heroes end their Town Stay and cannot enter this Town for a week. Every time the Posse enters for a Town Stay, a Random Hero makes a Cunning 6+ test. If three successes are made on a single roll, this vile secret is discovered and this Town is Destroyed.", restrictions: [] },
  { roll: 12, name: "Dark Secret", flavor: "Something sinister lurks beneath the surface of this town.", effect: "Whenever the Posse enters this Town, all Heroes make a Luck 4+ roll. If failed, Attack! — Draw a Threat at the Posse's Threat level. If this fight is failed or Escaped, Destroy one Town Location.", restrictions: ["Reroll if Town already has the 'Peaceful' trait"] },
  { roll: 13, name: "No Stones Allowed!", flavor: "The people here are fed up with Dark Stone.", effect: "You may not buy or sell any Dark Stone, Gear with the Dark Stone symbol, or any Dark Stone Upgrades while in this Town.", restrictions: ["Reroll if the Town is the Mining Town type"] },
  { roll: 14, name: "Dark Stone Infused", flavor: "The earth itself radiates with Dark Stone corruption.", effect: "Each Hero takes 1 Corruption Hit for each day that they stay here during a Town Visit.", restrictions: [] },
  { roll: 15, name: "Shortages", flavor: "Supplies are hard to come by out here.", effect: "Side Bag Tokens may not be bought here, but may be sold for twice the listed price. Also, whenever a Hero wants to buy a Purchase Item, roll a D6. On a 1, 2, or 3, that Item is not in stock.", restrictions: ["Reroll if the Town is the Mining Town or Rail Town type"] },
  { roll: 16, name: "Obligation", flavor: "A Random Hero has some sort of financial obligation in this Town.", effect: "That hero must pay D3×$50 whenever visiting this Town or else gain 1 Corruption point with no Willpower save.", restrictions: [] },
  { roll: 21, name: "Degenerate", flavor: "Rough folk with no respect for proper company.", effect: "Any Female Hero that visits a Town Location without a Male Hero is at risk of being assaulted. If unaccompanied, make a Strength 4+ test. If failed, the Female Hero takes Hits (1 Damage) and rolls on the Injury Chart if she suffers more than three Wounds.", restrictions: ["Reroll if the Town has the keyword 'Law' or the trait 'Law-Abiding'"] },
  { roll: 22, name: "Bad Water", flavor: "Whatever's in the water, it ain't doing anybody any favors.", effect: "At the start of each day, every Hero makes a Strength 4+ test. If failed, they are at −1 Health until the end of your next Mission.", restrictions: [] },
  { roll: 23, name: "Inbred", flavor: "Folks here can't figure out anything too complicated.", effect: "You may only Purchase Items in this Town. All other Services, Rituals, or other actions are unavailable.", restrictions: [] },
  { roll: 24, name: "Xenophobic", flavor: "Mutants aren't welcome here.", effect: "Heroes with any Mutations roll twice for Location Events and always take the lesser of the two results. This Town should never include the Mutant Quarter Location.", restrictions: ["Reroll if Town has the keyword 'Mutant' or is the Mutant Town type"] },
  { roll: 25, name: "Unstable Gate", flavor: "Something tears at the fabric of space around here.", effect: "Whenever a Hero would visit a Town Location, go to a Random Town Location instead.", restrictions: [] },
  { roll: 26, name: "Foreigners", flavor: "Outsiders are viewed with deep suspicion.", effect: "Whenever the Posse enters this Town, all Heroes make a Luck 4+ roll. If failed, Attack! — Draw a Threat at the Posse's Threat level. If this fight is failed or Escaped, Destroy one Town Location.", restrictions: ["Reroll if Town has the 'Peaceful' trait"] },
  { roll: 31, name: "Heathens", flavor: "Religion is not welcome here.", effect: "Heroes with the keyword 'Holy' roll twice for Location Events and always take the lesser of the two results. Replace the Church with another Location if it is set up in this Town.", restrictions: ["Reroll if Town already has the 'Religious Cult' trait or keyword 'Holy' or is the Plague Town type"] },
  { roll: 32, name: "Cannibals!", flavor: "The people of this Town have taken to questionable practices.", effect: "Whenever the Posse enters this Town, Attack! — Roll a Human Threat at the Hero Posse's level. If all Heroes are KO'd during this fight, all Heroes roll on the Injury Chart three times. The Heroes may not stay at this Town (not even at the Camp Site).", restrictions: [] },
  { roll: 33, name: "Religious Cult", flavor: "The faithful demand absolute devotion.", effect: "Heroes that do not have the keyword 'Holy' roll twice for Location Events and always take the lesser of the two results. There must always be a Church in this Town. Replace another Location with the Church if it is ever Destroyed.", restrictions: ["Reroll if Town already has the 'Heathens' trait"] },
  { roll: 34, name: "Boring", flavor: "Folks here are boring as hell.", effect: "Remove any other Town Traits/Types/Keywords from this Town and do not roll for any other Traits.", restrictions: [] },
  { roll: 35, name: "Bartering", flavor: "Cash is meaningless here — trade is king.", effect: "Gold may not be used to Purchase Items. All Items traded directly for Items or Services are worth their listed sell value; no change is given if overpaid.", restrictions: [] },
  { roll: 36, name: "Corrupt", flavor: "Everyone here has their hand out.", effect: "Each Hero must pay a $25 bribe for each day they stay in Town or else end their Town Visit immediately.", restrictions: ["Reroll if the Town has the keyword 'Law'"] },
  { roll: 41, name: "Thieving", flavor: "Pickpockets and thugs target the Posse the moment they arrive.", effect: "Whenever the Posse enters this Town, each Hero makes an Agility 4+ roll. If failed, that Hero has lost D3×$50 worth of Gold, Gear, or Side Bag Tokens (your choice).", restrictions: ["Reroll if the Town has the 'Law-Abiding' Trait or the keyword 'Law'"] },
  { roll: 42, name: "Slavers", flavor: "Bondage and servitude are the local economy.", effect: "Whenever you visit Town Locations, take D6 Corruption Hits. A Hero may attempt to free slaves by making a Strength 6+ test. If successful: Destroy Location, gain 50 XP, and end the Posse's Town Stay. You may not visit again for a week.", restrictions: [] },
  { roll: 43, name: "Amazonian", flavor: "Women run this town and they don't tolerate weakness from men.", effect: "Male Heroes roll twice for Location Events and always take the lesser of the two results.", restrictions: [] },
  { roll: 44, name: "Peaceful", flavor: "No weapons of any sort are permitted in this Town.", effect: "While in Town, Heroes do not have access to their weapons and may only use their fists in Combat. Heroes may not purchase or sell any Weapons, Ammunition, or Weapon Upgrades while in Town.", restrictions: ["Reroll if Town has the keyword 'Outlaw' or has the 'Unstable Gate' Trait or is the Outlaw Town type"] },
  { roll: 45, name: "Addicted", flavor: "The vices of this town are irresistible.", effect: "Each Hero makes an Agility 4+ roll each day they stay in Town. If failed, the Hero loses an Alcohol or Herb Side Bag Token (their choice).", restrictions: [] },
  { roll: 46, name: "Nightmares", flavor: "Darkness seeps into the sleep of all who rest here.", effect: "Each Hero takes 3 Horror Hits every day they stay in Town. Sanity Damage gained from this cannot be Healed until after you confront your fears and finish another Mission.", restrictions: [] },
  { roll: 51, name: "Artifact Decay", flavor: "Something in this Town is hostile to ancient relics.", effect: "Each Hero that carries any Artifacts rolls a D8 whenever they enter this Town. On a 1, add a Corruption token to an Artifact. With 3 Corruption Tokens, that Artifact is Destroyed.", restrictions: [] },
  { roll: 52, name: "Bad Luck", flavor: "Misfortune follows the Posse through every door.", effect: "At the beginning of each day in Town, all Heroes make a Luck 5+ roll. If failed, move the Darkness marker two spaces on the Town Event Tracker instead of the normal one per day.", restrictions: [] },
  { roll: 53, name: "Black Market", flavor: "Anything can be had here — for the right price.", effect: "Heroes may visit any Town Location, whether or not it officially exists in this Town. Prices are $50 more expensive for Purchase Items or Services at Black Market Locations (regular Town Locations have normal prices). If a Town Location is Destroyed, a Black Market Location replaces it. If all Town Locations are Destroyed, the Town itself is Destroyed.", restrictions: [] },
  { roll: 54, name: "Jovial", flavor: "Good cheer and good fortune seem to follow the Posse here.", effect: "When rolling on the Town Event chart, roll twice and take the higher of the two rolls.", restrictions: [] },
  { roll: 55, name: "Constructive", flavor: "Folks here rebuild what's been lost.", effect: "Whenever you enter Town, if any Town Locations have been Destroyed, the Posse rolls D8. If an 8 is rolled, add a new Town Location. This roll is not made again until another Mission is completed.", restrictions: [] },
  { roll: 56, name: "Cattle Yard", flavor: "Hard work pays off out here.", effect: "Instead of visiting a Town Location, a Hero may make an Agility or Strength Skill test for the day to earn money. For each roll of 2–5, gain $25. For every 6, gain $100. If a 1 is rolled, the Hero earns nothing and suffers an accident — roll on the Injury Chart.", restrictions: [] },
  { roll: 61, name: "Law-Abiding", flavor: "Folks here are proper and don't much tolerate disreputable persons.", effect: "Heroes with keyword 'Outlaw' roll twice for Location Events and always take the lesser of the two results. This Town should never include the Smuggler's Den Location.", restrictions: ["Reroll if Town type is an Outlaw Town or if the Town already has 'Degenerate' or 'Thieving' Trait or keyword 'Outlaw'"] },
  { roll: 62, name: "Fancy House", flavor: "There's something seedy going on behind those curtains.", effect: "Every night you stay in this Town, each Hero rolls a D8. On a 1 or 2, a Male Hero loses $50 and gains keyword 'Rash' (−3 Health; removed at Doc's Office via Surgery). On a roll of 8, that Hero instead loses $100 and may remove one Madness. Female Heroes who roll a 7 or 8 may gain $100.", restrictions: [] },
  { roll: 63, name: "Unstable Economy", flavor: "This town can never make up its mind.", effect: "Choose different Town Locations each time you come here for a Town Stay. Keyword Locations or Town Type Locations are the only constants; must still follow any restrictions.", restrictions: [] },
  { roll: 64, name: "Dimensional Paradox", flavor: "This town seems to exist in two places at once.", effect: "Pick a second, different Keyword or Town Type. Whenever you enter Town, roll a D6. On an even roll it is the 1st Town Keyword/Type; on an odd roll it is the 2nd. Locations stay the same and may conflict — it's a paradox.", restrictions: [] },
  { roll: 65, name: "Well-Defended", flavor: "This Town has Armor 5+.", effect: "Whenever a Town Location or the Town itself would be Destroyed, roll a D6. On a 5 or better, that Location or the Town is not Destroyed.", restrictions: [] },
  { roll: 66, name: "Unique Location", flavor: "There's an expert or artisan in Town renowned throughout the region.", effect: "Choose one of the Town's Locations at Random. You may purchase Advanced Gear and Services from this Location in this Town.", restrictions: [] },
];

export function lookupTownTrait(roll) {
  return townTraitsChart.find(e => Number(e.roll) === Number(roll)) || null;
}

export function rollD36TownTrait() {
  const d1 = Math.ceil(Math.random() * 6);
  const d2 = Math.ceil(Math.random() * 6);
  const roll = d1 * 10 + d2;
  return { roll, result: lookupTownTrait(roll) };
}
