export const injuryChart = [
  { roll: 11, name: "Eviscerated", flavor: "A brutal wound tears through vital organs.", effect: "Hero is Dead." },
  { roll: 13, name: "Foreign Object", flavor: "Something unnatural lodges itself in your flesh.", effect: "Roll D6 to lose gear slot or lose 3 Health permanently." },
  { roll: 14, name: "Spinal Cord Injury", flavor: "Your back cracks with a sickening crunch.", effect: "-1 Agility and Strength (min 1)." },
  { roll: 15, name: "Brain Injury", flavor: "A concussive blow scrambles your senses.", effect: "-1 Cunning and Lore (min 1)." },
  { roll: 16, name: "Butchered Genitals", flavor: "A savage strike lands below the belt with devastating effect.", effect: "-1 Spirit and Luck (min 1)." },
  { roll: 21, name: "Fractured Hip", flavor: "Your movement becomes labored and painful.", effect: "1 Hit after every Move action." },
  { roll: 22, name: "Mangled Hand", flavor: "Twisted fingers and bone make combat more difficult.", effect: "-1 Carrying slot, no Critical Hits with that hand." },
  { roll: 23, name: "Gouged Eye", flavor: "Your vision blurs as blood runs from the socket.", effect: "No Critical Hits with Ranged Weapons." },
  { roll: 24, name: "Fractured Ribs", flavor: "Every breath comes with a stab of pain.", effect: "-1 Carrying slot." },
  { roll: 25, name: "Broken Leg", flavor: "Your leg buckles under your weight.", effect: "-1 Move (min 1)." },
  { roll: 26, name: "Abdominal Trauma", flavor: "A deep wound leaves your guts churning.", effect: "-1 Defense (min 1)." },
  { roll: 31, name: "Concussion", flavor: "Your head spins and time seems to blur.", effect: "-1 Initiative and -1 Skill die until next Adventure." },
  { roll: 32, name: "Internal Bleeding", flavor: "You feel weak as blood pools inside.", effect: "Future rolls on this chart use D3x10+D3. -1 to Surgery recovery." },
  { roll: 33, name: "Broken Arm", flavor: "A loud crack signals the end of your arm's usefulness.", effect: "No Critical Hits with Melee Weapons." },
  { roll: 34, name: "Cracked Knee", flavor: "Each step sends pain shooting up your leg.", effect: "Push 1 space when Wounded." },
  { roll: 35, name: "Crushed Foot", flavor: "You limp from the agony.", effect: "-1 Escape (min 1)." },
  { roll: 36, name: "Scalped", flavor: "A wide slash removes more than just hair.", effect: "Cannot wear Head Clothing/Gear." },
  { roll: 41, name: "Slashed Face", flavor: "A disfiguring gash makes you harder to trust.", effect: "-1 on rolls in 'Stranger' Encounters (min 1)." },
  { roll: 42, name: "Broken Teeth", flavor: "Your jaw aches with every chew or shout.", effect: "1 Hit when using consumable Side Bag Token." },
  { roll: 43, name: "Broken Collar Bone", flavor: "Pain shoots down your arm whenever you lift it.", effect: "-1 Grit." },
  { roll: 44, name: "Chest Wound", flavor: "You breathe in shallow gasps, every move a strain.", effect: "-1 Initiative." },
  { roll: 45, name: "Severed Finger", flavor: "You count to nine now.", effect: "Ranged Weapons are -1 Shot (min 1)." },
  { roll: 46, name: "Severed Ear", flavor: "You barely heard that coming.", effect: "Considered Ambushed by 1 Enemy (+2 Initiative)." },
  { roll: 51, name: "Swollen Eye", flavor: "Vision swells shut on one side.", effect: "Line of Sight limited; 1 Move to change facing." },
  { roll: 52, name: "Pulled Muscle", flavor: "Movement causes sharp, stabbing pain.", effect: "Half-move next turn after taking Wounds." },
  { roll: 53, name: "Twisted Ankle", flavor: "Every step sends lightning up your leg.", effect: "No diagonal movement until end of Adventure." },
  { roll: 54, name: "Sprained Wrist", flavor: "Your grip is weak and unstable.", effect: "-1 Ranged (min 1) until end of Adventure." },
  { roll: 55, name: "Dislocated Shoulder", flavor: "You can barely lift your arm.", effect: "-1 Melee (min 1) until end of Adventure." },
  { roll: 56, name: "Rattled", flavor: "You can't shake the shock from your system.", effect: "-1 to Skill Tests (min 1) until end of Adventure." },
  { roll: 61, name: "Photophobia", flavor: "Bright lights make your head pound.", effect: "-1 To-Hit if on same tile as Light Source (min 1)." },
  { roll: 62, name: "Breathing Difficulties", flavor: "Each breath is a wheeze and a struggle.", effect: "Cannot spend Grit to move." },
  { roll: 63, name: "Puncture Wound", flavor: "A deep stab continues to throb with every movement.", effect: "-1 Combat until end of Adventure." },
  { roll: 64, name: "Busted Jaw", flavor: "Speaking and eating are excruciating.", effect: "+$25 to all Purchases until next Mission." },
  { roll: 65, name: "Wind Knocked Out", flavor: "You're dazed, but not done.", effect: "No lasting effect." },
  { roll: 66, name: "Scarring", flavor: "A lasting mark of survival... and a tale to tell.", effect: "+1 Grit." }
];
